import { api } from './client'
import {
  createAdminEntityApi,
  type MergeResponse,
  type DeleteResponse
} from './adminFactory'

export type { MergeResponse, DeleteResponse }

export interface AdminUser {
  id: string
  name: string
  username: string
  verified: boolean
  is_admin: boolean
  created_at: string
}

export interface AdminProduct {
  id: string
  name: string
  brand: string | null
  unit: string | null
  verified: boolean
  created_at: string
}

export interface AdminStore {
  id: string
  name: string
  address: string | null
  chain: string | null
  verified: boolean
  created_at: string
}

export interface AdminGroup {
  id: string
  name: string
  created_by: string
  creator_name: string
  member_count: number
  created_at: string | null
}

// Type definitions for update data
export type UserUpdateData = {
  name: string
  username: string
  is_admin: boolean
  verified: boolean
}

export type ProductUpdateData = {
  name: string
  brand?: string | null
  unit?: string | null
}

export type StoreUpdateData = {
  name: string
  address?: string | null
  chain?: string | null
  opening_hours?: Record<string, string> | null
}

export interface AdminTag {
  id: string
  value: string
  type: string
  verified: boolean
  product_count: number
  created_at: string | null
}

export type TagUpdateData = {
  value: string
  type: string
}

// Create admin entity APIs using factory
const usersEntityApi = createAdminEntityApi<AdminUser, UserUpdateData>('users')
const productsEntityApi = createAdminEntityApi<AdminProduct, ProductUpdateData>('products')
const storesEntityApi = createAdminEntityApi<AdminStore, StoreUpdateData>('stores')
const tagsEntityApi = createAdminEntityApi<AdminTag, TagUpdateData>('tags')

export const adminApi = {
  // Users CRUD (generated by factory)
  getUsers: usersEntityApi.getAll,
  toggleUserVerification: usersEntityApi.toggleVerification!,
  updateUser: usersEntityApi.update,
  mergeUsers: usersEntityApi.merge,
  deleteUser: usersEntityApi.delete,

  // Products CRUD (generated by factory)
  getProducts: productsEntityApi.getAll,
  toggleProductVerification: productsEntityApi.toggleVerification!,
  updateProduct: productsEntityApi.update,
  mergeProducts: productsEntityApi.merge,
  deleteProduct: productsEntityApi.delete,

  // Stores CRUD (generated by factory)
  getStores: storesEntityApi.getAll,
  toggleStoreVerification: storesEntityApi.toggleVerification!,
  updateStore: storesEntityApi.update,
  mergeStores: storesEntityApi.merge,
  deleteStore: storesEntityApi.delete,

  // Tags CRUD (generated by factory)
  getTags: tagsEntityApi.getAll,
  toggleTagVerification: tagsEntityApi.toggleVerification!,
  updateTag: tagsEntityApi.update,
  mergeTags: tagsEntityApi.merge,
  deleteTag: tagsEntityApi.delete,

  // Settings and Groups (custom methods, not using factory)

  async getRegistrationSetting(): Promise<{ allow_registration: boolean }> {
    return await api.get<{ allow_registration: boolean }>('/admin/settings/registration')
  },

  async setRegistrationSetting(allowRegistration: boolean): Promise<{ allow_registration: boolean; message: string }> {
    return await api.post<{ allow_registration: boolean; message: string }>(`/admin/settings/registration?allow_registration=${allowRegistration}`)
  },

  async getGroups(search?: string, limit: number = 100, offset: number = 0): Promise<AdminGroup[]> {
    const params = new URLSearchParams()
    if (search) params.append('search', search)
    params.append('limit', limit.toString())
    params.append('offset', offset.toString())

    return await api.get<AdminGroup[]>(`/admin/groups?${params}`)
  },
}
