export { api, ApiError } from './client'
export { authApi } from './auth'
export { groupsApi } from './groups'
export { runsApi } from './runs'
export { shoppingApi } from './shopping'
export { storesApi } from './stores'
export { productsApi } from './products'
export { distributionApi } from './distribution'
export { searchApi } from './search'
export { notificationsApi } from './notifications'

export type { LoginRequest, RegisterRequest } from './auth'
export type { Group, GroupDetails, CreateGroupRequest } from './groups'
export type { RunDetail, CreateRunRequest, PlaceBidRequest } from './runs'
export type { ShoppingListItem, EncounteredPriceRequest, PurchaseRequest } from './shopping'
export type { Store, CreateStoreRequest } from './stores'
export type { ProductSearchResult, ProductDetail, CreateProductRequest } from './products'
export type { DistributionItem, TogglePickupRequest } from './distribution'
export type { SearchResults, SearchProduct, SearchStore, SearchGroup } from './search'
export type { GetNotificationsParams } from './notifications'
