"""Add is_helper to run_participations

Revision ID: 2f9fd584c644
Revises: 
Create Date: 2025-10-24 09:33:06.199841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f9fd584c644'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encountered_prices_encountered_at'), table_name='encountered_prices')
    op.drop_index(op.f('ix_encountered_prices_encountered_by'), table_name='encountered_prices')
    op.drop_index(op.f('ix_encountered_prices_product_id'), table_name='encountered_prices')
    op.drop_index(op.f('ix_encountered_prices_store_id'), table_name='encountered_prices')
    op.drop_table('encountered_prices')
    op.add_column('group_membership', sa.Column('is_group_admin', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('groups', sa.Column('invite_token', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('is_joining_allowed', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('groups', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # Generate unique tokens for existing groups
    op.execute("""
        UPDATE groups
        SET invite_token = LOWER(
            SUBSTRING(MD5(RANDOM()::TEXT || id::TEXT) FROM 1 FOR 8)
        )
        WHERE invite_token IS NULL
    """)

    # Now make it NOT NULL and add unique index
    op.alter_column('groups', 'invite_token', nullable=False)
    op.create_index(op.f('ix_groups_created_by'), 'groups', ['created_by'], unique=False)
    op.create_index(op.f('ix_groups_invite_token'), 'groups', ['invite_token'], unique=True)
    op.create_index('ix_reassignment_requests_run_status', 'leader_reassignment_requests', ['run_id', 'status'], unique=False)
    op.create_index('ix_reassignment_requests_to_user_status', 'leader_reassignment_requests', ['to_user_id', 'status'], unique=False)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'read', 'created_at'], unique=False)
    op.create_index('ix_product_availabilities_product_store', 'product_availabilities', ['product_id', 'store_id'], unique=False)
    op.create_index('ix_product_availabilities_store_created', 'product_availabilities', ['store_id', 'created_at'], unique=False)
    op.add_column('product_bids', sa.Column('participation_id', sa.UUID(), nullable=True))
    op.add_column('product_bids', sa.Column('distributed_quantity', sa.Integer(), nullable=True))
    op.add_column('product_bids', sa.Column('distributed_price_per_unit', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('product_bids', sa.Column('is_picked_up', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('product_bids', sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product_bids', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('product_bids', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_product_bids_participation_id'), 'product_bids', ['participation_id'], unique=False)
    op.create_index('ix_product_bids_participation_product', 'product_bids', ['participation_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_product_bids_product_id'), 'product_bids', ['product_id'], unique=False)
    op.drop_constraint(op.f('product_bids_run_id_fkey'), 'product_bids', type_='foreignkey')
    op.drop_constraint(op.f('product_bids_user_id_fkey'), 'product_bids', type_='foreignkey')
    op.create_foreign_key(None, 'product_bids', 'run_participations', ['participation_id'], ['id'])
    op.drop_column('product_bids', 'run_id')
    op.drop_column('product_bids', 'user_id')
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('unit', sa.String(), nullable=True))
    op.add_column('products', sa.Column('verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('products', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('verified_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_products_created_by'), 'products', ['created_by'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_verified_by'), 'products', ['verified_by'], unique=False)
    op.drop_constraint(op.f('products_store_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['verified_by'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])
    op.drop_column('products', 'store_id')
    op.drop_column('products', 'base_price')
    op.add_column('run_participations', sa.Column('is_helper', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('run_participations', sa.Column('is_removed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('run_participations', sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_run_participations_run_id'), 'run_participations', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_participations_user_id'), 'run_participations', ['user_id'], unique=False)
    op.create_index('ix_run_participations_user_run', 'run_participations', ['user_id', 'run_id'], unique=False)
    op.add_column('runs', sa.Column('planned_on', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('planning_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('runs', sa.Column('active_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('shopping_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('adjusting_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('distributing_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_runs_group_id'), 'runs', ['group_id'], unique=False)
    op.create_index('ix_runs_group_state', 'runs', ['group_id', 'state'], unique=False)
    op.create_index(op.f('ix_runs_state'), 'runs', ['state'], unique=False)
    op.create_index(op.f('ix_runs_store_id'), 'runs', ['store_id'], unique=False)
    op.add_column('shopping_list_items', sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shopping_list_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('shopping_list_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index('ix_shopping_list_items_product', 'shopping_list_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_product_id'), 'shopping_list_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_run_id'), 'shopping_list_items', ['run_id'], unique=False)
    op.drop_column('shopping_list_items', 'encountered_prices')
    op.add_column('stores', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('stores', sa.Column('chain', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('opening_hours', sa.JSON(), nullable=True))
    op.add_column('stores', sa.Column('verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('stores', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('stores', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('stores', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stores', sa.Column('verified_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_stores_created_by'), 'stores', ['created_by'], unique=False)
    op.create_index(op.f('ix_stores_verified_by'), 'stores', ['verified_by'], unique=False)
    op.create_foreign_key(None, 'stores', 'users', ['verified_by'], ['id'])
    op.create_foreign_key(None, 'stores', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'verified')
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_index(op.f('ix_stores_verified_by'), table_name='stores')
    op.drop_index(op.f('ix_stores_created_by'), table_name='stores')
    op.drop_column('stores', 'verified_by')
    op.drop_column('stores', 'verified_at')
    op.drop_column('stores', 'created_by')
    op.drop_column('stores', 'created_at')
    op.drop_column('stores', 'verified')
    op.drop_column('stores', 'opening_hours')
    op.drop_column('stores', 'chain')
    op.drop_column('stores', 'address')
    op.add_column('shopping_list_items', sa.Column('encountered_prices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_shopping_list_items_run_id'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_product_id'), table_name='shopping_list_items')
    op.drop_index('ix_shopping_list_items_product', table_name='shopping_list_items')
    op.drop_column('shopping_list_items', 'updated_at')
    op.drop_column('shopping_list_items', 'created_at')
    op.drop_column('shopping_list_items', 'purchased_at')
    op.drop_index(op.f('ix_runs_store_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_state'), table_name='runs')
    op.drop_index('ix_runs_group_state', table_name='runs')
    op.drop_index(op.f('ix_runs_group_id'), table_name='runs')
    op.drop_column('runs', 'cancelled_at')
    op.drop_column('runs', 'completed_at')
    op.drop_column('runs', 'distributing_at')
    op.drop_column('runs', 'adjusting_at')
    op.drop_column('runs', 'shopping_at')
    op.drop_column('runs', 'confirmed_at')
    op.drop_column('runs', 'active_at')
    op.drop_column('runs', 'planning_at')
    op.drop_column('runs', 'planned_on')
    op.drop_index('ix_run_participations_user_run', table_name='run_participations')
    op.drop_index(op.f('ix_run_participations_user_id'), table_name='run_participations')
    op.drop_index(op.f('ix_run_participations_run_id'), table_name='run_participations')
    op.drop_column('run_participations', 'joined_at')
    op.drop_column('run_participations', 'is_removed')
    op.drop_column('run_participations', 'is_helper')
    op.add_column('products', sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_store_id_fkey'), 'products', 'stores', ['store_id'], ['id'])
    op.drop_index(op.f('ix_products_verified_by'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_created_by'), table_name='products')
    op.drop_column('products', 'verified_by')
    op.drop_column('products', 'verified_at')
    op.drop_column('products', 'created_by')
    op.drop_column('products', 'verified')
    op.drop_column('products', 'unit')
    op.drop_column('products', 'brand')
    op.add_column('product_bids', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('product_bids', sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_bids', type_='foreignkey')
    op.create_foreign_key(op.f('product_bids_user_id_fkey'), 'product_bids', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('product_bids_run_id_fkey'), 'product_bids', 'runs', ['run_id'], ['id'])
    op.drop_index(op.f('ix_product_bids_product_id'), table_name='product_bids')
    op.drop_index('ix_product_bids_participation_product', table_name='product_bids')
    op.drop_index(op.f('ix_product_bids_participation_id'), table_name='product_bids')
    op.drop_column('product_bids', 'updated_at')
    op.drop_column('product_bids', 'created_at')
    op.drop_column('product_bids', 'picked_up_at')
    op.drop_column('product_bids', 'is_picked_up')
    op.drop_column('product_bids', 'distributed_price_per_unit')
    op.drop_column('product_bids', 'distributed_quantity')
    op.drop_column('product_bids', 'participation_id')
    op.drop_index('ix_product_availabilities_store_created', table_name='product_availabilities')
    op.drop_index('ix_product_availabilities_product_store', table_name='product_availabilities')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_index('ix_reassignment_requests_to_user_status', table_name='leader_reassignment_requests')
    op.drop_index('ix_reassignment_requests_run_status', table_name='leader_reassignment_requests')
    op.drop_index(op.f('ix_groups_invite_token'), table_name='groups')
    op.drop_index(op.f('ix_groups_created_by'), table_name='groups')
    op.drop_column('groups', 'created_at')
    op.drop_column('groups', 'is_joining_allowed')
    op.drop_column('groups', 'invite_token')
    op.drop_column('group_membership', 'is_group_admin')
    op.create_table('encountered_prices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('minimum_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('encountered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('encountered_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['encountered_by'], ['users.id'], name=op.f('encountered_prices_encountered_by_fkey')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('encountered_prices_product_id_fkey')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('encountered_prices_store_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('encountered_prices_pkey'))
    )
    op.create_index(op.f('ix_encountered_prices_store_id'), 'encountered_prices', ['store_id'], unique=False)
    op.create_index(op.f('ix_encountered_prices_product_id'), 'encountered_prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_encountered_prices_encountered_by'), 'encountered_prices', ['encountered_by'], unique=False)
    op.create_index(op.f('ix_encountered_prices_encountered_at'), 'encountered_prices', ['encountered_at'], unique=False)
    # ### end Alembic commands ###
